Создаём и выводим моки
htmlacademy-ecmascript/65755-big-trip-13 pull request #4
Opened 2021-01-19 21:08 UTC by abatollo

2021-01-20 11:14 UTC, rideorgtfo requested changes

2021-01-20 11:14 UTC, rideorgtfo commented on src/main.js
> +const points = new Array(POINT_COUNT).fill().map(generatePoint).sort((firstEl, secondEl) => +dayjs(secondEl.date_from) - +dayjs(firstEl.date_from));
Приводить к числу лучше через ```Number(dayjs())``` или ```dayjs().valueOf()```.
Если где-то возникнет ошибка с типами, этот унарный плюс ты будешь долго искать.

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +    descriptionString += descriptionTextArray[randomIndex];
В твоем варианте алгоритма можно получить текст из одинаковых предложений.
На каждой итерации нужно удалять полученный вариант из массива чтобы этого избежать

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +  return descriptionString.trim();
Вместо того чтобы делать ```trim()```  можно сделать ```descriptionText.split(`.`);``` - по точке, не по точке и пробелу. Также это поможет выкинуть ```if (randomIndex !== descriptionTextArray.length - 1) {```

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +  const descriptionTextArray = descriptionText.split(`. `);
Константы нужно вынести из тела функции

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +  ];
Константы нужно вынести из тела функции

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +const Offer = [
Имена констант записываются в ```UPPER_SNAKE_CASE```

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +    [dateToKey]: dateToValue,
Давай в js не пользоваться snake_case для ключей в объектах. Все что приходит с сервера будет преобразовываться функцией-адаптером. Ее мы напишем позже

2021-01-20 11:14 UTC, rideorgtfo commented on src/mock/trip.js
> +  const offers = (getRandomInteger(0, 1)) ? offer.offers : ``;
Неявное преобразование типов, лучше сделать явным
```Boolean(getRandomInteger(0, 1)) ? offer.offers : ``;```

2021-01-20 11:14 UTC, rideorgtfo commented on src/view/event.js
> +  const {is_favorite: isFavorite} = point;
snake_case

2021-01-20 11:17 UTC, rideorgtfo commented on src/view/event.js
> +          <p class="event__duration">${dayjs(point.date_to).diff(point.date_from, `minutes`)}M</p>
Если длится больше часа, то формат ```1H 20M```

2021-01-20 11:28 UTC, rideorgtfo commented on src/mock/trip.js
> +const generateFavorites = () => Boolean(getRandomInteger(0, 1));
Тут проблемы с неймингом. Может ```generateIsFavorite```?
Эта функция точно нужна? В generatePoint вполне сойдет и ```Boolean(getRandomInteger(0, 1))```

2021-01-20 13:51 UTC, abatollo commented on src/mock/trip.js
> +  const offers = (getRandomInteger(0, 1)) ? offer.offers : ``;
На него выкидывается Redundant Boolean call  no-extra-boolean-cast

2021-01-20 21:37 UTC, rideorgtfo commented on src/mock/trip.js
> +const OFFER = [
```OFFERS```?

2021-01-20 21:37 UTC, rideorgtfo commented on src/mock/trip.js
> +  const filteredTrimedPlaceholderText = trimedPlaceholderText.filter(Boolean);
Это достаточно сделать один раз, а не каждый раз при вызове функции

2021-01-20 21:37 UTC, rideorgtfo commented on src/mock/trip.js
> +    if (!randomText.includes(filteredTrimedPlaceholderText[randomIndex])) {
Предлагаю алгоритм получше.
1. Копируем массив с предложениями
2. Берем из него случайный элемент
3. Удаляем его
4. Если нужно еще предложение, смотрим п.2

Так не придется просматривать предыдущие результаты с помощью ```includes```

2021-01-20 21:37 UTC, rideorgtfo commented on src/mock/trip.js
> +    offers: (getRandomInteger(0, 1)) ? offer.offers : ``,
Если нет офферов - пустой массив. Так как у тебя описаны все типы поездок в OFFERS, можно вовсе убрать условие

2021-01-21 12:46 UTC, rideorgtfo commented on src/mock/trip.js
> +    type: offer.type
Тут должно быть ровно наоборот. 
У точки есть собственный тип(type). Затем по этому типу нужно сгенерировать список активных офферов.
А при отрисовке нужно взять из моков все офферы по type и подсветить активные.

2021-01-21 12:47 UTC, rideorgtfo commented on src/mock/trip.js
> +    type: offer.type
Тут должно быть ровно наоборот. 
У точки есть собственный тип(type). Затем по этому типу нужно сгенерировать список активных офферов.
А при отрисовке нужно взять из моков все офферы по type и подсветить активные.

2021-01-22 09:12 UTC, rideorgtfo requested changes

2021-01-22 09:12 UTC, rideorgtfo commented on src/mock/trip.js
> +const OFFER_TYPES = [`taxi`, `bus`, `train`, `ship`, `transport`, `drive`, `flight`, `check-in`, `sightseeing`, `restaurant`];
Это не offer type. Это point type
Вполне подойдет название POINT_TYPES

2021-01-22 09:12 UTC, rideorgtfo commented on src/mock/trip.js
> +export const OFFERS_AND_TYPES = [
А это OFFERS

2021-01-22 09:12 UTC, rideorgtfo commented on src/view/event-edit.js
> +const findAvailableOffers = (type) => OFFERS_AND_TYPES.find((el) => el.type === type);
OFFERS лучше импортировать в main.js и доставлять сюда параметрами функции.
В дальнейшем этот массив будет приезжать с сервера, ты ведь не будешь ходить на сервер из вьюхи? :)

2021-01-22 09:12 UTC, rideorgtfo commented on src/view/event.js
> +  const {is_favorite: isFavorite} = point;
Все еще не поправлено

2021-01-22 09:12 UTC, rideorgtfo commented on src/view/event.js
> +            <time class="event__end-time" datetime="${dayjs(point.date_to).format(`YYYY-MM-DDTHH:mm`)}">${dayjs(point.dateTo).format(`H:mm`)}</time>
snake_case

2021-01-22 11:35 UTC, merged